os: linux
dist: xenial

git:
  depth: false

install: true

stages:
  - Build

jobs:
  include:
    - stage: Build
      name: Integration test against latest Docker
      before_install: ./install_docker.sh && ./configure_docker_tls.sh
      script: 
        - DOCKER_CERT_PATH=$HOME/.docker/certs DOCKER_TLS_VERIFY=1 DOCKER_HOST=tcp://localhost:2376 docker version
